---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: myapp-secret
  namespace: demo-prod
spec:
  encryptedData:
    DB_PASSWORD: AgA6eAmOWcOKLy6l3PdsiAE/ZalFj8Q3k5PFFWTKxZ1wyFd5KS7xUeOQmchF2Bvx1mrCXtgrHvWO51Unjiak6TegicyTSHMOKTyBBn+D6IlO37GNVwfCkBJD/kmXAf3kiB/onZ4J1anmeAv16cNAZngXCXMGFr8ppei5ElIlOz8Pc9gyo5HmLBOfJ6RG4OAeQi1a0PkPbK4Pxc+c/k407EjCrX6Hc3nPk83ERmBE3JoNAVCsFJwsAOHDbdUP0S0cTsAY0yC7rvy34ZAGks/iXDSccs3xTwZsDqK+SVCrunDHRiFWgnxQiYvJykbpsefhXefZ26aAlxhkd8JwQHNJpEttHXZSIaV0sPTIvR501d7V6BXgap0qKkZIMnp033d9Ez+iKLJl5lwjQO5HflyCQoASCwtKahW/bcIME3RZIGobPvZcvKqfM2dEiT8jZ01aqyp9p26cc5M1CH1bNLzNyh4w9zNolbwHLJJKORNVRsQyC098n0QVmNuwmPh6A4DhAEJ9TmLfWs3JgsS8INT3xaJvU6VENPWUFqqO0mV3ZEWw+xfbIrcBiSSeg9qVTn6AZgKH+tN5RzKg7XTg2QjDbD3h6DyP9EUImiAqxlHn4xI5PpkHPkJAyrd2lgMCp7m38D7sI8BGZnjoaYmfZzZ2iD7JcFcOCA561RzXlGGs5T0OJ0ht3HKUPv3y5HcT+itCzAtHXX/46MOkP9dcXg==
  template:
    metadata:
      name: myapp-secret
      namespace: demo-prod
    type: Opaque
