apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/Alawady/argocd-helm-lab.git
      revision: main
      directories:
      - path: environments/*
  template:
    metadata:
      name: myapp-{{path.basename}}
    spec:
      project: default
      source:
        repoURL: https://github.com/Alawady/argocd-helm-lab.git
        targetRevision: main
        path: myapp
        helm:
          valueFiles:
          - ../{{path}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-{{path.basename}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true      
