---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: myapp-secret
  namespace: demo-testing
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    DB_PASSWORD: AgA3YqBsxViheHZdFcQDUIO0n8292I9nQy+9khhzQRFm3vvYoAMXs20s/qSNMZY6AENSrG0cnIrHyOzzn83TjDrK6uDifLWf1PyNQh85d6llghxGpw41Byf9pBNTbhtROvGr3f6OyVvqSwnGQXuxvPJDE7f/FpK3u5A3dWVjUJZZvaGVggvPWeIUo6aMuBJkQv68H5/pHQXni2deXw8S9yA1ihKOI9SRSLXfYxnHGdb66Idl2ejDTMwREcGba38/ee3Ay2VlzKpJA0IWXPB+9JKJmhER5GnzG/LoLSd2sz7VK0IafKC6f/xTJDi0KWl3kdQTXI5sNiahQhRE5f0P86qfnJD/y3hBvRikC3EY0jAKr3u624LYAsZc/CsiIbXsmM/jHHNt4FGMe5YBWVRAFvfqancW8pvCKdn0MmhavhqRsD47bgS1dYZQtfutPJUyrGBOXgpitLwnDdrvDV0w12TkatyB2r3o+rDlqsmfvFxHvq8QgcZxIwYmomi+Ak2wVZDLP5KI4x8kB1agKoV6F7JN0OmaHclBlsk/DUk2Q3FNeQ6i3dfpRa3mXol+rzuF0vSbT5pu7L8cCKF0uA4nBorQYNwqeAOmE13rsU/LG6PWS/jRsgs0TCBpIqli1zkLk9ZQTz5aR1bEIbM/FHphVNNDqZe8gZN4+gqV/wbjFEa7sCsDpMbgl29b1ZmUaQ7DEFLAReOT4dv6sOWZFg==
  template:
    metadata:
      name: myapp-secret
      namespace: demo-testing